In [1]:
import os
import pandas as pd

organization_path = "data/Organization.xlsx"

organization_records = pd.read_excel(organization_path)
organization_records.head()

,__ID,CreateTime,zzCreationTS,zzModificationTS,_id_type,City,State,Zip,MailCity,MailState,...,z12MoAverage_House,z12MoAverage_Pounds,z12MoAverage_LlbsPerPerson,z12MoAverage_PeoplePerHouse,z12MoAverage_TEFAPCases,z12MoAverage_LlbsPerHH,z12MoAverage_Meals,zNameIfActiveBank,block_geoid,is_zip_centroid
0,1.0,System.Byte[],NaN,2026-05-15T19:15:18Z,11.0,Rochester,MN,55904.0,Rochester,MN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Channel One Regional Food Bank*,2.710900e+14,0.0
1,3.0,System.Byte[],NaN,2026-08-06T10:27:10Z,1.0,Brooklyn Park,MN,55428.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Second Harvest Heartland,2.705303e+14,0.0
2,5.0,System.Byte[],NaN,2026-09-01T02:10:43Z,1.0,East Grand Forks,MN,56721.0,East Grand Forks,MN,...,NaN,NaN,NaN,NaN,530.0,NaN,NaN,North Country Food Bank Inc.,2.711902e+14,0.0
3,6.0,System.Byte[],NaN,2026-09-03T10:32:32Z,1.0,Duluth,MN,55808.0,Duluth,MN,...,NaN,NaN,NaN,NaN,108.0,NaN,NaN,Second Harvest Northland,2.713700e+14,0.0
4,7.0,System.Byte[],NaN,2026-01-07T13:35:05Z,1.0,Fargo,ND,58102.0,Fargo,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.801700e+14,0.0

In [2]:
# How many rows and columns in organization_records
print("Number of rows:", len(organization_records))
print("Number of columns:", len(organization_records.columns))

Number of rows: 1202
Number of columns: 68

In [3]:
marketbucks_path = "data/marketbucksUsage.xlsx"
marketbucks_participation = pd.read_excel(marketbucks_path)
marketbucks_participation.head()

,_ID,zzCreationTS,zzCreationDate,zzModificationTS,_id_site,Dated,SNAPDistributed,SNAPRedeemed,MBDistributed,MBRedeemed,GiftCerts,RCGiftCertificates,PBDistributed,PBRedeemed,RCMBDistributed,RCMBRedeemed,Customers,Transactions,isLateEntry
0,7621,2022-01-06T12:46:33Z,2022-01-06,2025-12-30T13:52:32Z,14214,2022-01-04,0.00,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
1,7622,2022-01-06T12:48:30Z,2022-01-06,2025-12-30T13:52:32Z,14214,2022-01-04,52.61,52.61,8.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
2,7623,2022-01-06T12:49:57Z,2022-01-06,2025-12-30T13:52:32Z,14214,2022-01-05,337.72,337.72,85.0,85.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
3,7624,2022-01-13T10:01:03Z,2022-01-13,2025-12-30T13:52:32Z,14214,2022-01-12,26.74,26.74,7.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
4,7628,2022-01-14T09:42:31Z,2022-01-14,2025-12-30T13:52:32Z,14214,2022-01-13,59.09,59.09,50.0,50.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN

In [4]:
# How many rows and columns in marketbucks_participation
print("Number of rows:", len(marketbucks_participation))
print("Number of columns:", len(marketbucks_participation.columns))

Number of rows: 13573
Number of columns: 19

In [8]:
call_path = "data/Incoming Call.xlsx"
call_center_logs = pd.read_excel(call_path)
call_center_logs.head()

,__ID,zzCreationTS,zzModificationTS,zzModificationTSNotServer,zzLastArchived,Date,TimeStamp,CallTime,CallLength,CallMethod,...,isSNAPRx,ReferralInfoEntry,Referral Source,HowHear,FollowUpNeeded,FollowUpNeededDays,Follow up Date,isFollowup1Complete,FollowupDate2,isFollowup2Complete
0,119284,2024-09-11T13:54:54Z,2026-02-13T12:47:16Z,NaN,2025-05-19T15:21:57Z,2024-09-11,2024-09-11T13:54:54Z,13:54:54,NaN,Email,...,NaN,UW-211,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN
1,119285,2024-09-11T13:59:17Z,2026-02-13T12:47:16Z,NaN,2025-09-22T13:41:39Z,2024-09-11,2024-09-11T13:59:17Z,13:59:17,NaN,SNAP Rx,...,1.0,SNAP Info Given\nMNBenefits\nFood Shelf,Southwest State University,NaN,Other,0.0,2024-09-13,1.0,NaT,NaN
2,119286,2024-09-11T14:09:22Z,2026-02-13T12:47:16Z,NaN,2025-09-22T13:41:39Z,2024-09-11,2024-09-11T14:09:22Z,14:09:22,NaN,Voice Mail,...,NaN,SUN Bucks Hotline,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN
3,119287,2024-09-11T14:07:38Z,2026-02-13T12:47:16Z,NaN,2025-09-22T13:41:39Z,2024-09-11,2024-09-11T14:07:38Z,14:07:38,1-5 minutes,Chat Ticket,...,NaN,UW-211,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN
4,119288,2024-09-11T14:09:54Z,2026-02-13T12:47:16Z,NaN,2025-05-19T15:21:57Z,2024-09-11,2024-09-11T14:09:54Z,14:09:54,1-5 minutes,Live Call,...,NaN,County Office,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN

In [9]:
# How many rows and columns in call_center_logs
print("Number of rows:", len(call_center_logs))
print("Number of columns:", len(call_center_logs.columns))

Number of rows: 49727
Number of columns: 31

In [11]:
food_path = "data/org_FSStats.xlsx"
food_shelf_activity = pd.read_excel(food_path)
food_shelf_activity.head()

,__ID,_id_site,_Year,_Month,DateForSearch,zzCreationTS,zzModificationTS,AdultsReg,ChildrenReg,HouseholdsReg,...,PoundsHoliday,PoundsTotal,AgencyType,_id_bank,SuperShelf,_YearMonth,PoundsPerIndiv,IndividualsPerHH,id_agency,PoundsPerHH
0,2753,1254.0,2022,1,2022-01-01,2022-01-10T21:48:14Z,2025-12-30T13:50:18Z,1519.0,1048.0,1027.0,...,NaN,41548.0,Brick and Mortar Site,6.0,NaN,202201,15.0,3.0,NaN,40.0
1,2762,14434.0,2022,1,2022-01-01,2022-01-10T15:01:29Z,2025-12-30T13:50:18Z,23.0,16.0,17.0,...,NaN,900.0,Brick and Mortar Site,1.0,NaN,202201,19.0,3.0,14434.0,53.0
2,12862,1069.0,2022,3,2022-03-01,2022-03-02T16:18:49Z,2026-09-02T20:20:24Z,281.0,27.0,220.0,...,NaN,21345.0,Food Shelf,14179.0,NaN,202203,62.0,2.0,16988.0,97.0
3,12863,1069.0,2022,1,2022-01-01,2022-03-08T09:50:31Z,2026-09-02T20:20:24Z,281.0,21.0,216.0,...,NaN,15684.0,Food Shelf,14179.0,NaN,202201,48.0,2.0,16988.0,73.0
4,12864,14680.1,2022,1,2022-01-01,2022-03-08T09:50:31Z,2025-12-30T13:50:24Z,142.0,93.0,91.0,...,NaN,5761.0,Tribal Program,14179.0,NaN,202201,22.0,3.0,NaN,63.0

In [12]:
# How many rows and columns in food_shelf_activity
print("Number of rows:", len(food_shelf_activity))
print("Number of columns:", len(food_shelf_activity.columns))

Number of rows: 28287
Number of columns: 58